name: Rust
env: 
  RUSTFLAGS: "-D warnings"
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cargo fmt check
      run: cargo fmt --all --check

    - name: Cargo check
      run: cargo check --workspace --all-targets

    - name: Cargo clippy
      run: cargo clippy --all-targets --all-features
    
    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
